### ISSUE TITLE
SofTalk Ver.1.93.36を使用すると、AviUtlにD&Dした音声の最後の部分が再生しない

### ISSUE THREAD

**Issue by nobitaki4837** [mikado394m/yukkuriutil1#1]
ゆくサクとSofTalk Ver.1.93.36を使用した環境でAviUtlにD&Dすると、D&Dした音声の最後の部分が再生しない現象が発生します。(SofTalk Ver.1.93.32では発生しません)

■不具合の現象が発生した環境
1. バージョン
・ゆくサク: 0.0.9.9
・SofTalk: 1.93.36
・AviUtl: 1.00
・AviUtl拡張編集プラグイン: 0.92
・OS: Windows 10 1809 32bit

2. フォルダー構成
・C:\aviutl - AviUtlと拡張編集プラグインを同じフォルダーに格納
・C:\YukkuriUtil - ゆくサクの全ファイルを格納
・C:\YukkuriUtil\softalk - SofTalkの全ファイルを格納

3. 設定
・ゆくサクとSofTalkは、デフォルトの設定値を使用しています。(Exoテンプレートを変更していません)
・AviUtlですが、ファイル→環境設定→システムの設定→「再生ウィンドウの動画再生をメインウィンドウに表示する」チェックボックスをオンにしています。他の設定はデフォルトの設定値を使用しています。

■不具合の再現手順
1. AviUtlを起動し、「設定メニュー」→「拡張編集の設定」を選択します。
2. 拡張編集画面で、右クリック→「新規プロジェクトの作成」を選択します。
3. 画像サイズ640×480、フレームレート30fps、音声レート44100Hzで新規プロジェクトを作成します。
4. ゆくサクを起動し、「字幕」に「今日は天気がいいので動画を作りたいです」を入力します。
5. ゆくサクからAviUtlにドラッグ＆ドロップします。
6. AviUtlで再生すると、「今日は天気がいいので動画を作りたいです」の最後の2文字「です」が再生されない現象が発生します。

■正常な動作
「不具合の再現手順」を実施したときに、手順6で、「今日は天気がいいので動画を作りたいです」の文章が最後まで再生します。

■備考
・この現象は、ゆくサク Ver.0.0.9.9とSofTalk Ver.1.93.36(2019/02/11)を組み合わせて使用したときに発生します。
・ゆくサク Ver.0.0.9.9と、1つ前のバージョンであるSofTalk Ver.1.93.32(2018/05/12)を組み合わせて使用したときは、この現象は発生しません。

**Comment by mikado394m** [comment]
SofTalk Ver.1.93.32 と SofTalk Ver.1.93.36 とで生成される音声が違います。
Ver.1.93.32 では文章「今日は天気がいいので動画を作りたいです」の「動画を」の後ろと「です」の後ろにウェイトが挿入されるのですが、 Ver.1.93.36 では挿入されません。

ゆくサクでは AviUtl に挿入する音声オブジェクトの長さを`声設定`にある`音声の長さ補正`の分(単位はミリ秒)だけ加算した値にするので、ウェイトがなくなった分文章の最後が再生されなくなったという形です。

なので、`音声の長さ補正`の値を0にすればこの問題は解決します。しかし、SofTalk Ver.1.93.36 と ゆくサク ver0.0.9.9 を同時に使うと句読点などのウェイトがおかしくなるという他の問題もあるので、問題が修正されるまでの間は SofTalk Ver.1.93.32 を使っていただくことをおすすめします。

**Comment by mashimaro386** [comment]
なぜかゆくサクで音声を入力してドラッグアンドドロップやると動画ファイルと動画の音声ファイルが出るんですけど
どうすれば良いですか？
