### ISSUE TITLE
音声が途切れる

### ISSUE THREAD

**Issue by matchandayoo** [mikado394m/yukkuriutil1#3]
なぜかaviutlのタイムラインにD&Dすると、音声が最後まで読み上げられずに途中で途切れてしまうため、自分でアイテムの長さを伸ばさなきゃいけません。
softalkのバージョンは、nicnico動画の説明に書いてあったバージョンでやっていますが、できません。どうしたら良いでしょうか？

**Comment by mikado394m** [comment]
(すでに Close されていますが)
ゆくサクの声設定の「音声の長さ補正」を「0」にすることで解決できると思います。
