### ISSUE TITLE
Windows新IMEを利用時、キーの入力の一部がスキップされる

### ISSUE THREAD

**Issue by ChibiBouningen** [mikado394m/yukkuriutil1#6]
### 症状
文章入力窓にて文字入力中、キーボードの入力がスキップされる
他のアプリケーションや古いバージョンのIME使用時は発生しないため、当アプリケーションのバグだと思われる
### 環境
windows10 20H2 64bit
YukkuriUtil ver0.0.9.9
外付けSSDにインストール
### 試したこと
Windows設定から
以前のバージョンの Microsoft IME を使う
にチェックを入れる→**問題は発生せず**
![image](https://user-images.githubusercontent.com/84241001/118370617-5e589780-b5e3-11eb-8f05-b62ef00c11d8.png)
アプリケーションをフォルダごとデスクトップに移動し実行→変化なし

**Comment by oriaca372m** [comment]
再現しませんでしたが、依存しているソフトウェアのバージョンを更新したものをリリースしてみたので(ver0.0.10.10)、もしかすると改善するかもしれません。お試し下さい。

**Comment by ChibiBouningen** [comment]
> 
> 
> 再現しませんでしたが、依存しているソフトウェアのバージョンを更新したものをリリースしてみたので(ver0.0.10.10)、もしかすると改善するかもしれません。お試し下さい。

返信ありがとうございます。アップデートお疲れ様です。
新バージョンに入れ替えても症状が改善することはありませんでした。
また、症状の一部に誤りがありました。
誤「キーボードの入力がスキップされる」正「全角文字入力時に文字をスペースキーで仮確定後、その次の1文字の入力がスキップされる」です。
Google日本語入力を導入したところこの問題は発生しないので、やはり新IMEとの相性が悪いのかもしれません。
新IMEそのもののバグも多いようなので、今後のOSアップデート時には確認してみようと思います。
